const books = [
  {
    id: 1,
    name: 'Pismo od zlata',
    author: 'Lena Manda',
    image: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/321192_w_0_0px.jpg',
    description:
      '„Pisma od zlata“ Lene Mande je emotivna priča o ljubavi, tajnama i snazi reči koje mogu promeniti nečiji život. Kroz nežan i dirljiv stil, knjiga vodi čitaoca kroz uspomene, emocije i poruke koje ostaju zauvek zapisane u srcu.',
    category: 'Ljubavni roman',
    city: 'Novi Sad',
    availableFrom: '2026-06-01',
    owner: 'Ana D.',
    rating: 5,
    numReviews: 12,
    status: 'Dostupna',
  },
  {
    id: 2,
    name: 'Crveni adresar',
    author: 'Sofija Lundberj',
    image: 'https://laguna.oozmi-cdn.com/images/4700cf46-42b3-4fbd-9380-33cca79f451c/crveni-adresar-sofija-lundberj-m-h300.webp',
    description:
        'Crveni adresar je dirljiva priča o uspomenama, ljubavi i ljudima koji ostavljaju trag u našem životu. Kroz stranice starog adresara, glavna junakinja se priseća svoje prošlosti i dokazuje da prava ljubav i najlepše uspomene nikada ne blede',
    category: 'Ljubavni roman',
    city: 'Beograd',
    availableFrom: '2026-06-10',
    owner: 'Maila S.',
    rating: 4.5,
    numReviews: 8,
    status: 'Dostupna',
  },
  {
    id: 3,
    name: 'Kafa na užarenom pesku',
    author: 'Lena Manda',
    image: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/300183_w_0_0px.jpg',
    description:
      'Kafa na užarenom pesku je roman o ženi koja se suočava sa monotonijom i nezadovoljstvom u braku, pa počinje da preispituje svoje životne izbore i emocije. Kroz priču o ljubavi, svakodnevnim problemima i ličnim dilemama, knjiga prikazuje uspone i padove običnih ljudi i potragu za srećom.',
    category: 'Drama',
    city: 'Nis',
    availableFrom: '2026-05-25',
    owner: 'Milica R.',
    rating: 4.8,
    numReviews: 16,
    status: 'Na razmeni',
  },
  {
    id: 4,
    name: 'Paša',
    author: 'Srđan Dragojević',
    image: 'https://laguna.oozmi-cdn.com/images/96bedefa-6220-42e6-b7a8-3fa001471417/Pasa-w560.avif',
    description:
      'Paša je istorijski roman inspirisan stvarnim događajima, koji prati prijateljstvo i sukob između crnogorskog knjaza Nikole Petrovića i Osman-paše, turskog vojskovođe. Priča kombinuje istoriju, humor i političke intrige u brzom i filmskom stilu pripovedanja',
    category: 'Istorijski roman',
    city: 'Subotica',
    availableFrom: '2026-07-05',
    owner: 'Jovana P.',
    rating: 4.9,
    numReviews: 21,
    status: 'Dostupna',
  },
  {
    id: 5,
    name: 'Teo iz Golden',
    author: 'Alen Livaj',
    image: 'https://laguna.oozmi-cdn.com/images/305f1bff-e4a0-4ec4-b095-be103a0ff2dd/Teo-iz-Goldena-h600.avif',
    description:
      'Teo iz Goldena je dirljiva priča o misterioznom čoveku koji dolazi u mali grad Golden i kroz razgovore sa ljudima otkriva njihove skrivene emocije, nade i tuge. Roman govori o dobroti, prijateljstvu i snazi ljudske povezanosti, uz toplu i emotivnu atmosferu koja podseća na knjige Fredrika Bakmana.',
    category: 'Drama',
    city: 'Novi Sad',
    availableFrom: '2026-06-03',
    owner: 'Lena V.',
    rating: 4.7,
    numReviews: 10,
    status: 'Dostupna',
  },
  {
    id: 6,
    name: 'Bezimena žena',
    author: 'Vanesa Monfort',
    image: 'https://laguna.oozmi-cdn.com/images/ab066273-68c0-4024-ab3c-ec7e88323021/Bezimena-zena-h1200.avif',
    description:
      'Bezimena žena prati sudbinu žene koja pokušava da pronađe svoj identitet i istinu o prošlosti kroz niz emotivnih i dramatičnih događaja. Roman istražuje teme ljubavi, tajni, porodičnih odnosa i unutrašnje snage žene suočene sa teškim odlukama.',
    category: 'Psihološki roman',
    city: 'Kragujevac',
    availableFrom: '2026-06-15',
    owner: 'Sara K.',
    rating: 4.6,
    numReviews: 14,
    status: 'Dostupna',
  },
  {
    id: 7,
    name: 'Milonga strasnih senki: I to je tango',
    author: 'Grupa autora',
    image: 'https://laguna.oozmi-cdn.com/images/c5db3006-2365-4a6a-ad66-3e8d977573ef/Milonga-strasnih-senki-h600.avif',
    description:
      'Milonga strasnih senki: i to je tango je zbirka priča više autora koje se bave strastima, ljubavlju i mračnijim stranama ljudskih odnosa, povezanim kroz atmosferu tanga i argentinske milonge. Kroz različite stilove pisanja, knjiga prikazuje emocije, sudbine i trenutke koji se prepliću između stvarnosti i igre osećanja.',
    category: 'Zbirka priča',
    city: 'Novi Sad',
    availableFrom: '2026-06-08',
    owner: 'Katarina M.',
    rating: 4.9,
    numReviews: 19,
    status: 'Dostupna',
  },
  {
    id: 8,
    name: 'Madmoazel Alijansa',
    author: 'Nataša Lester',
    image: 'https://laguna.oozmi-cdn.com/images/297d32bb-c9aa-41ef-ba45-6f76897e927c/Madmoazel-Alijansa-h600.avif',
    description:
      'Madmoazel alijansa (Nataša Lester) je istorijski roman koji prati mladu ženu u Parizu tokom Drugog svetskog rata, koja se suočava sa opasnostima okupacije i pokušava da sačuva umetnost, ljubav i sopstveni identitet. Kroz priču o modi, špijunaži i hrabrosti, roman prikazuje snagu žena u teškim istorijskim okolnostima.',
    category: 'Istorijski roman',
    city: 'Beograd',
    availableFrom: '2026-06-18',
    owner: 'Tamara V.',
    rating: 4.7,
    numReviews: 13,
    status: 'Dostupna',
  },
  {
    id: 9,
    name: 'Vladarke iz praiskona',
    author: 'Katarina Mitrović',
    image: 'https://laguna.oozmi-cdn.com/images/cc5570f0-154c-486e-9559-a255d553cc93/Vladarke-iz-Praiskona-h600.avif',
    description:
      'Vladarke iz praiskona (Katarina Mitrović) je knjiga koja kroz spoj mitologije i fikcije prati priče moćnih ženskih likova iz davnih vremena, prikazujući njihove borbe, mudrost i uticaj na svet oko sebe. Roman istražuje poreklo moći, legendi i ženskih arhetipova kroz maštovitu i simboličnu priču.',
    category: 'Mitološka proza',
    city: 'Nis',
    availableFrom: '2026-07-01',
    owner: 'Ivana S.',
    rating: 4.8,
    numReviews: 17,
    status: 'Dostupna',
  },
  {
    id: 10,
    name: 'Zemlja slatke VEČNOSTI',
    author: 'Harper Li',
    image: 'https://laguna.oozmi-cdn.com/images/8d8c84de-7a96-4401-813d-a263c88af69d/Zemlja-slatke-vecnosti-h600.avif',
    description:
      'Savremeni roman (drama) koji govori o životu, gubicima i potrazi za smirenjem nakon teških iskustava, kroz emotivnu priču o porodici i ličnim borbama.',
    category: 'Savremeni roman',
    city: 'Subotica',
    availableFrom: '2026-07-01',
    owner: 'Ivana S.',
    rating: 3.7,
    numReviews: 6,
    status: 'Dostupna',
  },
  {
    id: 11,
    name: 'Bleda vatra',
    author: 'Vladimir Nabakov',
    image: 'https://laguna.oozmi-cdn.com/images/1a132940-9678-45e1-94e5-6dcc412cb557/bleda-vatra-vladimir-nabokov-v-h1200.avif',
    description:
      '„Bleda vatra“ (Pale Fire) je roman Vladimira Nabokova koji je napisan kao dugačka pesma jednog pesnika, uz opsežan i često ironičan komentar njegovog neobičnog suseda. Kroz igru pripovedanja, identiteta i skrivene poruke, roman se pretvara u složenu zagonetku o istini i ludilu.',
    category: 'Postmoderni roman',
    city: 'Valjevo',
    availableFrom: '2026-07-01',
    owner: 'Ivana S.',
    rating: 4.0,
    numReviews: 5,
    status: 'Dostupna',
  },
  {
    id: 12,
    name: 'Pisma iz Šampanje',
    author: 'Kejt Mekintoš',
    image: 'https://laguna.oozmi-cdn.com/images/51cf3044-4750-4030-b75b-8938811f044c/pisma-iz-sampanje-h600.avif',
    description:
      '„Pisma iz Šampanje“ (Kate Macintosh) je istorijski roman koji prati sudbinu žena i porodica tokom Prvog svetskog rata u francuskoj regiji Šampanja, kroz razmenu pisama koja otkrivaju ljubav, gubitke i nadu. Priča spaja ratnu stvarnost sa intimnim emocijama i svakodnevnim borbama ljudi koji pokušavaju da prežive teška vremena.',
    category: 'Ratna drama',
    city: 'Vranje',
    availableFrom: '2026-07-01',
    owner: 'Ivana S.',
    rating: 4.8,
    numReviews: 10,
    status: 'Dostupna',
  },
];

export default books;


